<?php 
// Put any random info like a list of states or countries here. 
$config['states'] = array(
	array(
		"abbreviation"=>"AL",
		"state"=>"alabama"
	),
	array(
		"abbreviation"=>"AK",
		"state"=>"alaska"
	),
	array(
		"abbreviation"=>"AZ",
		"state"=>"arizona"
	),
	array(
		"abbreviation"=>"AR",
		"state"=>"arkansas"
	),
	array(
		"abbreviation"=>"CA",
		"state"=>"california"
	),
	array(
		"abbreviation"=>"CO",
		"state"=>"colorado"
	),
	array(
		"abbreviation"=>"CT",
		"state"=>"connecticut"
	),
	array(
		"abbreviation"=>"DE",
		"state"=>"delaware"
	),
	array(
		"abbreviation"=>"DC",
		"state"=>"district of columbia"
	),
	array(
		"abbreviation"=>"FL",
		"state"=>"florida"
	),
	array(
		"abbreviation"=>"GA",
		"state"=>"georgia"
	),
	array(
		"abbreviation"=>"HI",
		"state"=>"hawaii"
	),
	array(
		"abbreviation"=>"ID",
		"state"=>"idaho"
	),
	array(
		"abbreviation"=>"IL",
		"state"=>"illinois"
	),
	array(
		"abbreviation"=>"IN",
		"state"=>"indiana"
	),
	array(
		"abbreviation"=>"IA",
		"state"=>"iowa"
	),
	array(
		"abbreviation"=>"KS",
		"state"=>"kansas"
	),
	array(
		"abbreviation"=>"KY",
		"state"=>"kentucky"
	),
	array(
		"abbreviation"=>"LA",
		"state"=>"louisiana"
	),
	array(
		"abbreviation"=>"ME",
		"state"=>"maine"
	),
	array(
		"abbreviation"=>"MD",
		"state"=>"maryland"
	),
	array(
		"abbreviation"=>"MA",
		"state"=>"massachusetts"
	),
	array(
		"abbreviation"=>"MI",
		"state"=>"michigan"
	),
	array(
		"abbreviation"=>"MN",
		"state"=>"minnesota"
	),
	array(
		"abbreviation"=>"MS",
		"state"=>"mississippi"
	),
	array(
		"abbreviation"=>"MO",
		"state"=>"missouri"
	),
	array(
		"abbreviation"=>"MT",
		"state"=>"montana"
	),
	array(
		"abbreviation"=>"NE",
		"state"=>"nebraska"
	),
	array(
		"abbreviation"=>"NV",
		"state"=>"nevada"
	),
	array(
		"abbreviation"=>"NH",
		"state"=>"new hampshire"
	),
	array(
		"abbreviation"=>"NJ",
		"state"=>"new jersey"
	),
	array(
		"abbreviation"=>"NM",
		"state"=>"new mexico"
	),
	array(
		"abbreviation"=>"NY",
		"state"=>"new york"
	),
	array(
		"abbreviation"=>"NC",
		"state"=>"north carolina"
	),
	array(
		"abbreviation"=>"ND",
		"state"=>"north dakota"
	),
	array(
		"abbreviation"=>"OH",
		"state"=>"ohio"
	),
	array(
		"abbreviation"=>"OK",
		"state"=>"oklahoma"
	),
	array(
		"abbreviation"=>"OR",
		"state"=>"oregon"
	),
	array(
		"abbreviation"=>"PN",
		"state"=>"pennsylvania"
	),
	array(
		"abbreviation"=>"PR",
		"state"=>"puerto rico"
	),
	array(
		"abbreviation"=>"RI",
		"state"=>"rhode island"
	),
	array(
		"abbreviation"=>"SC",
		"state"=>"south carolina"
	),
	array(
		"abbreviation"=>"SD",
		"state"=>"south dakota"
	),
	array(
		"abbreviation"=>"TN",
		"state"=>"tennessee"
	),
	array(
		"abbreviation"=>"TX",
		"state"=>"texas"
	),
	array(
		"abbreviation"=>"UT",
		"state"=>"utah"
	),
	array(
		"abbreviation"=>"VT",
		"state"=>"vermont"
	),
	array(
		"abbreviation"=>"VA",
		"state"=>"virginia"
	),
	array(
		"abbreviation"=>"WA",
		"state"=>"washington"
	),
	array(
		"abbreviation"=>"WV",
		"state"=>"west virginia"
	),
	array(
		"abbreviation"=>"WI",
		"state"=>"wisconsin"
	),
	array(
		"abbreviation"=>"WY",
		"state"=>"wyoming"
	),
	array(
		"abbreviation"=>"OT",
		"state"=>"other"
	)
);