<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title></title>

    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">

    <!--[if lt IE 9]>
    <script src="<?php echo base_url(); ?>static/js/vendor/html5shiv.js"></script>
    <![endif]-->

    <link rel="stylesheet"  href="<?php echo base_url(); ?>static/css/normalize.css"> <?php // We only need one Reset, if replacing please list why in commit messages ?>
    <link rel="stylesheet" href="<?php echo base_url(); ?>static/css/main.css">
</head>
<body>
<?php /*
<div id="loader" class="full">
	<div class="background-color"></div>
	<div class="load-container">
		<img src="<?php echo base_url(); ?>static/images/loading.gif" alt="loading" />
	</div>
</div>
*/ ?>
	
<div id="wrapper">
    <header class="clearfix">
		<div id="logo">
       		<a href="<?php echo base_url(); ?>"><img src="<?php echo base_url(); ?>static/images/rumblefish-logo.png" /></a>
			<div id="loader" class="small">
				<div class="load-container">
					<?php if ( $this->data->user->type == "admin" ) : ?>
						<img src="<?php echo base_url(); ?>static/images/oag_loading.gif" alt="loading" />
					<?php else: ?>
						<img src="<?php echo base_url(); ?>static/images/loading_small.gif" alt="loading" />
					<?php endif; ?>
				</div>
			</div>
		</div>
		<div id="welcome-the-user">
			<ul>
				<?php if ( Core_Model::LoggedIn() ) : ?>
				<li>Welcome: <a href="<?php echo base_url(); ?>user/account"><?php echo $user->user_name; ?></a></li>
				<li id="login-logout-action">
					<a href="<?php echo base_url(); ?>user/logout" id="user-logout">
						Logout
					</a>
				</li>
	            <?php endif; ?>
			</ul>
		</div>
    </header>

	<div id="container">
		<section id="player">
			
		</section>
		
		<nav id="navbar">
        	<ul>
				<?php 
					if ( Core_Model::LoggedIn() && Core_Controller::isAdmin() ) :
						$this->load->view('admin/navigation', $data);
					elseif( Core_Model::LoggedIn() && $page->top->meta->display_child_nav ) :
						foreach ( $page->top->children as $child ) :
							echo '<li><a href="'.$child->url.'">'.$child->title.'</a></li>';
						endforeach;
		        	endif; 
				?>
	        </ul>
		</nav>
		
	    <section id="body">
	    	
			
			
	    </section>
	
	
		<p>Copyright <?php echo date("Y"); ?> Rumblefish, Inc.</p>
		<p><a href="<?php echo base_url(); ?>terms-of-service">Terms of Service</a></p>
	</div>
</div>

<script id="template-title" type="text/template">
    {{ title }} - Rumblefish Backstage
</script>

<div class="message" id="login-message">
	<!-- Generated by Javascript -->
</div>

<?php
if ( Core_Controller::isAdmin() ) :

	$this->load->view('admin/dashboard');
	
	// Users
	$this->load->view('admin/users');
	$this->load->view('admin/documents-form');

    // Pages Admin
	$this->load->view('admin/pages-edit');
	$this->load->view('admin/pages-view');
	
	// Permissions Admin
	$this->load->view('permissions/roles-view');
	$this->load->view('permissions/roles-edit');
	
	// Catalogs
	$this->load->view('admin/catalogs/view');
	$this->load->view('admin/catalogs/form');
	$this->load->view('admin/catalogs/licenses');
	
	// Portals
	$this->load->view('admin/portals/view');
	$this->load->view('admin/portals/form');
	$this->load->view('admin/portals/licenses');
	$this->load->view('admin/portals/catalogs');
	
	// licenses
	$this->load->view('admin/licenses/view');
	$this->load->view('admin/licenses/form');
	$this->load->view('admin/licenses/details');

endif;
if ( Core_Model::LoggedIn() ) :
	
	// User Account Stuff
	$this->load->view('user/dashboard');
	$this->load->view('user/account');
	$this->load->view('user/songwriters');
	$this->load->view('user/firsttime');
	
	// Artists
	$this->load->view('artist/view');
	$this->load->view('artist/form');
	$this->load->view('artist/details');

	// User Account Stuff
	$this->load->view('user/dashboard');
	$this->load->view('user/change-password');
	
	$this->load->view('assets/trackform');
	$this->load->view('assets/albumform');
	$this->load->view('assets/viewtracks');
	$this->load->view('assets/viewalbums');
	$this->load->view('assets/user-search');
	$this->load->view('assets/manage');

	$this->load->view('playlists/view');

endif;
	
	$this->load->view('admin/login');
	$this->load->view('pages/default');
	$this->load->view('user/register');
	$this->load->view('user/reset-password');
	$this->load->view('user/confirm-success');

?>

	<script src="<?php echo base_url(); ?>static/js/vendor/jquery-1.8.2.min.js"></script>
	<script src="<?php echo base_url(); ?>static/js/vendor/jquery.lightbox_me.js"></script>
	<script src="<?php echo base_url(); ?>static/js/vendor/underscore.js"></script>
	<script src="<?php echo base_url(); ?>static/js/vendor/backbone.js"></script>
	<script src="<?php echo base_url(); ?>static/js/vendor/handlebars.js"></script>
	<script src="<?php echo base_url(); ?>static/js/vendor/jquery-ui-1.9.2.custom.min.js"></script>
	<script src="<?php echo base_url(); ?>static/js/vendor/advanced-parser-rules.js"></script>
	<script src="<?php echo base_url(); ?>static/js/vendor/wysihtml5-0.3.0.min.js"></script>

	<script src="<?php echo base_url(); ?>static/js/plugins.js"></script>
	<script type="text/javascript">
	    var path = '<?php echo base_url(); ?>',
			debug = false; 
	</script>
	<script src="<?php echo base_url(); ?>static/js/main.js"></script>
</body>
</html>
